-- stored procedures creation and test

USE RetailPulse_DWH;
GO

-- 1. Dynamic Monthly Revenue Performance & Growth Analytics
CREATE OR ALTER PROCEDURE usp_MonthlyRevenue
    @TargetYear INT
AS
BEGIN
    SET NOCOUNT ON;

    -- Using a CTE to compute sequential positions for MoM variance calculations
    WITH MonthlyMetrics AS (
        SELECT 
            d.MonthNumber,
            d.MonthName,
            SUM(fs.NetRevenueUSD) AS NetRevenue_USD,
            SUM(fs.ProfitUSD) AS TotalProfit_USD
        FROM FactSales fs
        JOIN DimDate d ON fs.DateKey = d.DateKey
        JOIN DimStatus s ON fs.StatusKey = s.StatusKey
        WHERE d.[Year] = @TargetYear
          AND s.StatusName NOT IN ('Cancelled', 'Refunded')
        GROUP BY d.MonthNumber, d.MonthName
    )
    SELECT 
        MonthName,
        NetRevenue_USD,
        TotalProfit_USD,
        -- Window function to calculate comparative growth metrics automatically
        ROUND(NetRevenue_USD - LAG(NetRevenue_USD, 1) OVER (ORDER BY MonthNumber), 2) AS AbsoluteGrowth_USD,
        ROUND(((NetRevenue_USD - LAG(NetRevenue_USD, 1) OVER (ORDER BY MonthNumber)) / 
               NULLIF(LAG(NetRevenue_USD, 1) OVER (ORDER BY MonthNumber), 0)) * 100, 2) AS GrowthRatePercentage
    FROM MonthlyMetrics
    ORDER BY MonthNumber;
END;
GO


-- 2. Customer Profile Value Deep-Dive (Instant CRM integration mockup)
CREATE OR ALTER PROCEDURE usp_CustomerLifetimeValue
    @OperationalCustomerID INT
AS
BEGIN
    SET NOCOUNT ON;

    -- Directly isolates specific operational keys while aggregating warehouse metrics
    SELECT 
        c.CustomerID,
        c.CustomerName,
        c.CustomerSegment,
        loc.Country AS DemographyCountry,
        COUNT(DISTINCT fs.OrderID) AS TotalOrdersPlaced,
        SUM(fs.Quantity) AS TotalItemsPurchased,
        SUM(fs.NetRevenueUSD) AS HistoricalSpend_USD,
        SUM(fs.ProfitUSD) AS NetContributionProfit_USD
    FROM FactSales fs
    JOIN DimCustomer c ON fs.CustomerKey = c.CustomerKey
    JOIN DimLocation loc ON c.LocationKey = loc.LocationKey
    WHERE c.CustomerID = @OperationalCustomerID
      AND c.IsCurrent = 1 -- Only pull active SCD profile snapshot
    GROUP BY c.CustomerID, c.CustomerName, c.CustomerSegment, loc.Country;
END;
GO


-- 3. Top Performing Catalog Products Evaluator
CREATE OR ALTER PROCEDURE usp_TopProducts
    @TopN INT
AS
BEGIN
    SET NOCOUNT ON;

    -- Dynamically restrains row generation counts based on consumer parameters
    SELECT TOP (@TopN)
        p.ProductName,
        p.Category,
        p.Brand,
        SUM(fs.Quantity) AS TotalUnitsSold,
        SUM(fs.NetRevenueUSD) AS GeneratedRevenue_USD,
        SUM(fs.ProfitUSD) AS NetProfit_USD
    FROM FactSales fs
    JOIN DimProduct p ON fs.ProductKey = p.ProductKey
    JOIN DimStatus s ON fs.StatusKey = s.StatusKey
    WHERE s.StatusName = 'Completed'
    GROUP BY p.ProductName, p.Category, p.Brand
    ORDER BY NetProfit_USD DESC;
END;
GO

-- test the procedures one by one

-- Test 1: Let's see the month-over-month growth for 2025
EXEC usp_MonthlyRevenue @TargetYear = 2025;

-- Test 2: Find a customer's lifetime metrics (Using an ID generated by our seed script)
EXEC usp_CustomerLifetimeValue @OperationalCustomerID = 2005;

-- Test 3: Show me the top 3 most profitable products across the entire warehouse
EXEC usp_TopProducts @TopN = 3;

USE RetailPulse_DWH;
GO

-- 4. Inventory Turnover Analytics by Product Category
CREATE OR ALTER PROCEDURE usp_InventoryTurnover
    @TargetCategory VARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    -- Financial reporting logic: Cost of Goods Sold (COGS) vs Average Inventory Asset Value
    SELECT 
        p.Category,
        p.SubCategory,
        p.ProductName,
        SUM(fi.StockSold) AS TotalUnitsSold,
        -- COGS = Units Sold * Standard Product Cost
        ROUND(SUM(fi.StockSold * p.StandardCost), 2) AS COGS_USD,
        -- Average Inventory = (Opening Stock + Closing Stock) / 2
        ROUND(AVG((fi.OpeningStock + fi.ClosingStock) / 2.0 * p.StandardCost), 2) AS AverageInventoryValue_USD,
        -- Turnover Ratio = COGS / Average Inventory Value
        ROUND(
            SUM(fi.StockSold * p.StandardCost) / 
            NULLIF(AVG((fi.OpeningStock + fi.ClosingStock) / 2.0 * p.StandardCost), 0), 
            2
        ) AS InventoryTurnoverRatio
    FROM FactInventory fi
    JOIN DimProduct p ON fi.ProductKey = p.ProductKey
    WHERE p.Category = @TargetCategory
    GROUP BY p.Category, p.SubCategory, p.ProductName
    ORDER BY InventoryTurnoverRatio DESC;
END;
GO


-- 5. Deep-Dive Marketing Campaign ROI Optimization Engine
CREATE OR ALTER PROCEDURE usp_MarketingCampaignROI
    @ChannelFilter VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    -- Combines structural ad costs from FactMarketing with actual attribution conversions
    SELECT 
        c.CampaignName,
        c.Channel,
        SUM(fm.Impressions) AS Impressions,
        SUM(fm.Clicks) AS Clicks,
        ROUND((CAST(SUM(fm.Clicks) AS DECIMAL(18,2)) / NULLIF(SUM(fm.Impressions), 0)) * 100, 3) AS CTR_Percentage, -- Click-Through Rate
        SUM(fm.Conversions) AS Conversions,
        SUM(fm.Cost) AS TotalCampaignCost_USD,
        -- Pulling true matched sales value linked to this campaign from FactSales
        ISNULL(SUM(fs.NetRevenueUSD), 0) AS AttributionRevenue_USD,
        -- ROI Calculation = (Attribution Revenue - Campaign Cost) / Campaign Cost
        ROUND(
            (ISNULL(SUM(fs.NetRevenueUSD), 0) - SUM(fm.Cost)) / NULLIF(SUM(fm.Cost), 0), 
            2
        ) AS ReturnOnInvestmentRatio
    FROM FactMarketing fm
    JOIN DimCampaign c ON fm.CampaignKey = c.CampaignKey
    LEFT JOIN FactSales fs ON fs.CampaignKey = c.CampaignKey AND fs.DateKey = fm.DateKey
    WHERE c.Channel = @ChannelFilter
    GROUP BY c.CampaignName, c.Channel
    ORDER BY ReturnOnInvestmentRatio DESC;
END;
GO

-- tests for the last 2 procedures

-- Test 4: Check inventory health metrics for the 'Sports' category
EXEC usp_InventoryTurnover @TargetCategory = 'Sports';

-- Test 5: Analyze the ROI performance of all 'Facebook Ads' campaigns
EXEC usp_MarketingCampaignROI @ChannelFilter = 'Facebook Ads';

